//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCKRM.Installer.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_us() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCKRM.Installer.Language.en_us", typeof(en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copy StreamingAssets/assets...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string assetsCopy {
            get {
                return ResourceManager.GetString("assetsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backup...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Choose a project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string chooseAProject {
            get {
                return ResourceManager.GetString("chooseAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Damaged project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string damagedProject {
            get {
                return ResourceManager.GetString("damagedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decompressing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string decompressing {
            get {
                return ResourceManager.GetString("decompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected version - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string detectedVersion {
            get {
                return ResourceManager.GetString("detectedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download Complete!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The downloaded project is corrupted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadDamagedProject {
            get {
                return ResourceManager.GetString("downloadDamagedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no project downloaded과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadedNoProject {
            get {
                return ResourceManager.GetString("downloadedNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no version file in the downloaded project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadedProjectNoVersionFile {
            get {
                return ResourceManager.GetString("downloadedProjectNoVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloaded version - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadedVersion {
            get {
                return ResourceManager.GetString("downloadedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gakkou Gurashi
        ///anime is fun과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string easterEgg {
            get {
                return ResourceManager.GetString("easterEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Installation finished!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string installationFinished {
            get {
                return ResourceManager.GetString("installationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you continue, everything in the SC KRM folder will be deleted!
        ///Would you like to continue?
        ///(The StreamingAssets folder only deletes files within the sc-krm namespace, and the rest of the files are overwritten only by the files to be installed.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string installWarning {
            get {
                return ResourceManager.GetString("installWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Newest version - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string newestVersion {
            get {
                return ResourceManager.GetString("newestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No project과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string noProject {
            get {
                return ResourceManager.GetString("noProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No project selected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string noProjectSelected {
            get {
                return ResourceManager.GetString("noProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No version file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string noVersionFile {
            get {
                return ResourceManager.GetString("noVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string overwrite {
            get {
                return ResourceManager.GetString("overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite project settings with defaults?
        ///(Only the settings you want to install are affected, not the settings you add)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string overwriteProjectSettings {
            get {
                return ResourceManager.GetString("overwriteProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy StreamingAssets/pack.*...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string packCopy {
            get {
                return ResourceManager.GetString("packCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge the settings of the downloaded project and the selected project...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string projectSettingsJsonMerge {
            get {
                return ResourceManager.GetString("projectSettingsJsonMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy SC KRM...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sckrmCopy {
            get {
                return ResourceManager.GetString("sckrmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete SC KRM...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sckrmDelete {
            get {
                return ResourceManager.GetString("sckrmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy SC-KRM-Version files...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sckrmVersionCopy {
            get {
                return ResourceManager.GetString("sckrmVersionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected project - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string selectedProject {
            get {
                return ResourceManager.GetString("selectedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected Project Setting Deserialize...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string selectedProjectSettingDeserialize {
            get {
                return ResourceManager.GetString("selectedProjectSettingDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
