//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCKRM.Installer.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ko_kr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko_kr() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCKRM.Installer.Language.ko_kr", typeof(ko_kr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   StreamingAssets/assets 복사...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string assetsCopy {
            get {
                return ResourceManager.GetString("assetsCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   백업...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 선택과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string chooseAProject {
            get {
                return ResourceManager.GetString("chooseAProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   손상된 프로젝트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string damagedProject {
            get {
                return ResourceManager.GetString("damagedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   압축 푸는 중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string decompressing {
            get {
                return ResourceManager.GetString("decompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   감지된 버전 - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string detectedVersion {
            get {
                return ResourceManager.GetString("detectedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드 완료!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadComplete {
            get {
                return ResourceManager.GetString("downloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드한 프로젝트가 손상되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadDamagedProject {
            get {
                return ResourceManager.GetString("downloadDamagedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드한 프로젝트가 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadedNoProject {
            get {
                return ResourceManager.GetString("downloadedNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드한 프로젝트에 버전 파일이 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadedProjectNoVersionFile {
            get {
                return ResourceManager.GetString("downloadedProjectNoVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드한 버전 - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string downloadedVersion {
            get {
                return ResourceManager.GetString("downloadedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치 완료!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string installationFinished {
            get {
                return ResourceManager.GetString("installationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   계속하면 SC KRM 폴더의 모든 항목이 삭제됩니다!
        ///계속하시겠습니까?
        ///(StreamingAssets 폴더는 기존 파일을 건드리지 않고 설치할 파일만 덮어씁니다.)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string installWarning {
            get {
                return ResourceManager.GetString("installWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   최신 버전 - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string newestVersion {
            get {
                return ResourceManager.GetString("newestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string noProject {
            get {
                return ResourceManager.GetString("noProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 프로젝트 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string noProjectSelected {
            get {
                return ResourceManager.GetString("noProjectSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   버전 파일 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string noVersionFile {
            get {
                return ResourceManager.GetString("noVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   덮어쓰기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string overwrite {
            get {
                return ResourceManager.GetString("overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 설정을 기본값으로 덮어쓰시겠습니까?
        ///(설치할 설정만 영향을 받고 사용자가 추가한 설정은 영향을 받지 않습니다)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string overwriteProjectSettings {
            get {
                return ResourceManager.GetString("overwriteProjectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StreamingAssets/pack.* 복사...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string packCopy {
            get {
                return ResourceManager.GetString("packCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   다운로드한 프로젝트와 선택한 프로젝트의 설정을 병합...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string projectSettingsJsonMerge {
            get {
                return ResourceManager.GetString("projectSettingsJsonMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   새로고침과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SC KRM 복사...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sckrmCopy {
            get {
                return ResourceManager.GetString("sckrmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SC KRM 삭제...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sckrmDelete {
            get {
                return ResourceManager.GetString("sckrmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SC-KRM-Version 파일 복사...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string sckrmVersionCopy {
            get {
                return ResourceManager.GetString("sckrmVersionCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 프로젝트 - 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string selectedProject {
            get {
                return ResourceManager.GetString("selectedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택한 프로젝트 설정 직렬화 해제...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string selectedProjectSettingDeserialize {
            get {
                return ResourceManager.GetString("selectedProjectSettingDeserialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
